name: HubEssentials
version: 1.0
main: com.MCNation.hub.Main

commands:
  help:
    description: Simple help command.
  teleport:
    description: Teleports players.
  setwarp:
    description: Sets the warp. 
  warp:
    description: Uses the warp function.
  warps:
    description: Lists the warps.
  kick:
    description: Kicks a player.
  ban:
    description: Bans a player.
  setBalance:
    description: adds shit to your acc.
  getBalance:
    description: gets shit
  tpall:
    description: tps
  nick:
    description: does shit
  spawnmob:
    description: idk
  setspawn:
    description: setsspawn